### ISSUE TITLE
INFOGRAFIA 

### ISSUE THREAD

**Issue by JeroRoque** [SistemasTecTlaxiaco/actividad-1-infografia-JeroRoque#2]
[Infografía_De_Ciclo_De_Vida_De_Un_ Sistema_Jeronima_Roque.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-JeroRoque/files/12489828/Infografia_De_Ciclo_De_Vida_De_Un_.Sistema_Jeronima_Roque.pdf)

**Comment by Arlet04** [comment]
Partes de la infografía : 4
Coherencia: 3
Organización: 4
Diseño: 4
Creatividad : 4
Calificación 19/20
Buen Trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
